routes/web.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Support\Facades\Route;

Route::view('/', 'welcome');




Route::prefix('admin')->group(function () {
    Route::get('login', [Auth\LoginController::class, 'showLoginForm'])->name('admin.login');
    Route::post('login', [Auth\LoginController::class, 'login'])->name('admin.login.submit');
    Route::post('logout', [Auth\LoginController::class, 'logout'])->name('admin.logout');

    Route::group(['middleware' => 'auth:admin'], function () {
        Route::view('/home', 'admin.home')->name('admin.home');
        Route::view('/my-profile', 'admin.profile')->name('admin.profile');
        Route::put('/my-profile', [HomeController::class, 'updateProfile'])->name('admin.updateProfile');

        Route::resources([
            'admins' => AdminController::class,
            'schools' => SchoolController::class,
            'students' => StudentController::class,
        ]);

        Route::post('students/{id}/set-order', [StudentController::class,'setOrder'])->name('students.setOrder');
    });
});

resources/views/admin/admins/_form.blade.php
<div class="row_form">
    <div class="form-group mb-3">
        {!! Form::label('name', 'الاسم', ['class' => 'form-label']) !!}
        {!! Form::text('name', null, ['class' => 'form-control', 'readonly' => $readonly]) !!}
        <x-forms.errors name="name" />
    </div>

    <div class="form-group mb-3">
        {!! Form::label('email', 'البريد الالكتروني', ['class' => 'form-label']) !!}
        {!! Form::email('email', null, ['class' => 'form-control', 'readonly' => $readonly]) !!}
        <x-forms.errors name="email" />
    </div>

    <div class="form-group mb-3">
        {!! Form::label('phone', 'الهاتف', ['class' => 'form-label']) !!}
        {!! Form::text('phone', null, ['class' => 'form-control', 'readonly' => $readonly]) !!}
        <x-forms.errors name="phone" />
    </div>

    @if (!$readonly)
        <div class="form-group mb-3">
            {!! Form::label('password', 'الرقم السري', ['class' => 'form-label']) !!}
            {!! Form::password('password', ['class' => 'form-control']) !!}
            <x-forms.errors name="password" />
        </div>

        <div class="form-group mb-3">
            {!! Form::label('password_confirmation', ' تاكيد الرقم السري ', ['class' => 'form-label']) !!}
            {!! Form::password('password_confirmation', ['class' => 'form-control']) !!}
            <x-forms.errors name="password_confirmation" />
        </div>
    @endif


    <div class="form-group mb-3">
        {!! Form::label('active', 'تفعيل', ['class' => 'form-label']) !!}
        {!! Form::select('active', active(), null, ['class' => 'form-control', 'disabled' => $readonly, 'placeholder' => 'اختر قيمة']) !!}
        <x-forms.errors name="active" />
    </div>

    @if (!$readonly)
        <div class="form-actions">
            <button type="submit" class="btn btn-primary"> حفظ</button>
        </div>
    @endif
</div>

resources/views/admin/admins/create.blade.php
@extends('admin.layouts.master')

@section('title', 'المشرفين')

@section('content')
    <div class="card-box">
        <h3 class="form-title font-green">اضافة مدير جديد</h3>

        {!! Form::open(['route' => 'admins.store']) !!}
        @include('admin.admins._form',['readonly'=>false, 'admin' => null])
        {!! Form::close() !!}

    </div>
@endsection

resources/views/admin/admins/edit.blade.php
@extends('admin.layouts.master')

@section('title', 'المشرفين')


@section('content')
    <div class="card-box">
        <h3 class="form-title font-green">تعديل الموظف: {{ $admin->name }}</h3>

        {!! Form::model($admin, ['route' => ['admins.update', $admin], 'method' => 'PUT']) !!}
        @include('admin.admins._form',['readonly'=>false])
        {!! Form::close() !!}

    </div>
@endsection

resources/views/admin/admins/index.blade.php
@extends('admin.layouts.master')

@section('title', 'المشرفين')

@section('content')

    <div class="card-box">
        <h4 class="mt-0 header-title">عرض المشرفين</h4>
        <p class="text-muted font-14 mb-3">
            <a href="{{ route('admins.create') }}" class="btn btn-info">اضافة جديد</a>
        </p>

        <div id="datatable-buttons_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
            <div class="row">
                <div class="col-sm-12 col-md-6">

                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap">
                        <thead>
                            <tr role="row">
                                <th class="sorting_asc" aria-controls="datatable-buttons" aria-sort="ascending">ID</th>
                                <th class="sorting" aria-controls="datatable-buttons">الاسم</th>
                                <th class="sorting" aria-controls="datatable-buttons">البريد الالكتروني</th>
                                <th class="sorting" aria-controls="datatable-buttons">الهاتف</th>
                                <th class="sorting" aria-controls="datatable-buttons">التفعيل</th>
                                <th class="sorting" aria-controls="datatable-buttons">العمليات</th>
                            </tr>
                        </thead>

                        <tbody>

                            @foreach ($admins as $admin)
                                <tr role="row" class="odd" id="row-{{ $admin->id }}">
                                    <td class="sorting_1">{{ $admin->id }}</td>
                                    <td>{{ $admin->name }}</td>
                                    <td>{{ $admin->email }}</td>
                                    <td>{{ $admin->phone }}</td>
                                    <td>
                                        @if ($admin->active)
                                            <h6 class="btn btn-success btn-circule"> مفعل</h6>
                                        @else
                                            <h6 class="btn btn-danger"> غير مفعل</h6>
                                        @endif
                                    </td>
                                    <td>
                                        {{-- <a href="{{ route('admins.show', $admin) }}" class="btn btn-success">استعراض</a> --}}
                                        <a href="{{ route('admins.edit', $admin) }}" class="btn btn-info">تعديل</a>
                                        @if ($admin->id !== auth('admin')->user()->id)
                                            <h6 class="btn btn-danger" data-name="{{ $admin->name }}"
                                                data-url="{{ route('admins.destroy', $admin) }}"
                                                onclick="delete_form(this)">
                                                حذف
                                            </h6>
                                        @endif
                                    </td>
                                </tr>

                            @endforeach

                        </tbody>
                    </table>

                    <form style="display: none;" id="delete_form" method="post">
                        @csrf @method('DELETE')
                    </form>

                </div>
            </div>

        </div>
    </div>


@endsection

@include('admin.layouts.partials.datatables')

resources/views/admin/admins/show.blade.php
@extends('admin.layouts.master')

@section('title', 'الموظفين')

@section('content')
    <div class="card-box">
        <h3 class="form-title font-green">عرض بيانات الموظف: {{ $admin->name }}</h3>

        {!! Form::model($admin) !!}
        @include('admin.admins._form',['readonly' => true])

        <div class="form-group">
            <a href="{{ route('admins.index') }}" class="btn btn-info">الرجوع</a>
        </div>
    </div>

@endsection